import config
#from selenium import webdriver
from selenium.webdriver.common.by import By
from jinja2 import Environment, FileSystemLoader
from selenium import webdriver
import os
import time

#GOOGLE_CHROME_PATH = ' /usr/bin/google-chrome-stable'
#CHROMEDRIVER_PATH = '/usr/lib/chromium-browser/chromedriver'

chrome_options = webdriver.ChromeOptions()
#chrome_options.add_argument('--disable-gpu')
#chrome_options.add_argument('--no-sandbox')

#chrome_options.binary_location = GOOGLE_CHROME_PATH
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
chrome_options.add_argument('--headless')
chrome_options.add_argument("--disable-dev-shm-sage")
chrome_options.add_argument("--no-sandbox")
"""
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument('--ignore-certificate-errors')
options.add_argument('--incognito')
options.add_argument('--headless')
driver = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver", chrome_options=options)
"""
 
driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)
 

from datetime import datetime

datetime.today().strftime('%Y-%m-%d')


driver.get("https://kenyacovid19.herokuapp.com")
time.sleep(20)
#driver.save_screenshot('screenie.png')

liveConfirmed = driver.find_element(By.ID, "confirmedValue").text
liveDead = driver.find_element(By.ID, "deathsValue").text
liveRecoverd = driver.find_element(By.ID, "recoveredValue").text


element = driver.find_element_by_tag_name('body')
element_png = element.screenshot_as_png
with open("screenie.png", "wb") as file:
    file.write(element_png)


import smtplib

# import the corresponding modules
from email import encoders
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


smtp_server = "smtp.gmail.com"
login = "" # paste your login generated by Mailtrap
password = "" # paste your password generated by Mailtrap

subject = "COVID 19:KENYA STATS UPDATES {}".format(datetime.today().strftime('%Y-%m-%d'))
sender_email = ""
receiver_email = []

then = datetime(2020,3,12)
todaystr = datetime.today().strftime('%Y-%m-%d')
today = datetime.today()
timediff = then - today

message = MIMEMultipart()
message["From"] = sender_email
message["To"] = ", ".join(receiver_email) 
message["Subject"] = subject
body = "Fellow Kenyan, \n Today,{} marks {} days since the first confirmed case of the Coronavirus Disease was recorded in our country.As a web developer,in patnership with the Kenyan Government, I moved quickly to implement a comprehensive plan designed to update you on the virus and its spread within our communities.For the first time in Kenyan history i'll like to introduce you to the Kenya Covid-19 Stats Dashboard.https://kenyacovid19.herokuapp.com/ .In that regard,the total number of confirmed cases are {}.Stay safe".format(todaystr,timediff.days,liveConfirmed)
print(body)

html = """\
 
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>For Edu or Org Design</title>

    <style>
        @media screen and (max-width: 600px) {
            .remove-flex-mobile {
                display: block !important;
            }
            .remove-flex-basis-mobile {
                flex-basis: unset !important;
                padding-left: 0 !important;
            }
            .display-grid-mobile {
                grid-template-columns: 1fr !important;
            }
            .reminders-list {
                padding-left: 15px !important;
                margin-top: 10px !important;
            }
            .reminders-table td {
                float: unset !important;
                display: block !important;
                width: unset !important;
                margin-left: 0 !important;
            }
            .second-item-order {
                flex-direction: column !important;
                align-items: flex-start !important;
            }
            .flex-order {
                order: 2 !important;
            }
            .list-header {
                padding-top: 20px !important;
            }
            .navigation-footer {
                text-align: center !important;
            }
            .navigation-footer li {
                display: list-item !important;
                padding: 10px 0 !important;
            }
            .social-media img {
                width: 30px !important;
            }
            .social-media a {
                padding: 0 3px 0 0 !important;
            }
            .social-media a:last-of-type {
                padding-right: 0 !important;
            }
        }
    </style>
</head>
<body style="margin:0;">
<table style="border: none; margin: 0 auto ; padding: 0;">
    <tr>
        <td style="padding: 0; background-color: #FFFFFF;">

            <div style="max-width: 600px; min-width: 200px; font-family: 'Arial', sans-serif; font-size: 16px; background-color: #FFFFFF; line-height: 1.4; color: #4A4A4A; border: 1px solid #DFDFDF; border-radius: 10px; overflow: hidden;">

                <div style="background-color: #e8c547; height: 60px;">
                </div>

                <header style="text-align: center;">
                    <h1 style="font-size: 58px;color: #30323d; background: #FFFFFF; margin-top: 30px; margin-bottom: 0; text-transform: uppercase;">LATEST NEWS</h1>
                    <p style="margin: 0; padding-bottom: 30px; font-size:18px;">Stay in the loop</p>
                </header>

                <div style="padding: 0 20px;">
                    <img src="cid:Mailtrapimage" alt="email hero image"
                         style="display: block; background-size: cover; width: 100%;">
                </div>

                <h2 style="font-size: 32px; padding: 30px 20px 0 20px; margin-bottom: 0; text-transform: uppercase; color: #4A4A4A;">STATS YOU MIGHT HAVE MISSED</h2>

                <ul style="padding: 0 20px;">
                        <li style="list-style-type: none; padding-bottom: 50px;padding-left: 20px; margin-left: 0;color: #4d5061;">
                          Today: """ +str(todaystr) + """
                                </br><p></p>
                            <div style="flex-basis: 100%; padding-left: 20px; width: 100%;"
                                 class="remove-flex-basis-mobile">
                                </br>
                                </br>
                                    <p style="padding-bottom: 20px; margin-top: 0; color: #4A4A4A">
                                       Day : """ +str(timediff.days) + """                               </p></br>
<!--                                    <h3 style="text-transform: uppercase; font-size: 28px; margin-top: 0; margin-bottom: 10px; color: #4A4A4A" class="list-header">DANCE TROUPE AUDITIONS</h3>-->
                                    <p style="padding-bottom: 20px; margin-top: 0; color: #4A4A4A">
                                       Confirmed Cases : """ +str(liveConfirmed) + """                                </p></br>
                                    </br>
                                    <a href="https://devngecu.herokuapp.com/" style="text-decoration: none; text-transform:
                                    uppercase; cursor: pointer; line-height: 1.1em; letter-spacing: 0; padding: 12px;
                                     background: #e8c547; color: #4A4A4A; border-radius: 8px; text-align: center;
                                     font-size: 16px; font-weight: bold; box-sizing: border-box;">DROP COMMENT</a>
                                  </br>
                                    <a href="https://kenyacovid19.herokuapp.com/" style="text-decoration: none; text-transform:
                                    uppercase; cursor: pointer; line-height: 1.1em; letter-spacing: 0; padding: 12px;
                                     background: #e8c547; color: #4A4A4A; border-radius: 8px; text-align: center;
                                     font-size: 16px; font-weight: bold; box-sizing: border-box;">MORE INFO</a>
                            </div>
                                </br>
                                


                        </li>


            </ul>

            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                        <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                                <span class="apple-link"
                                      style="color: #999999; font-size: 12px; text-align: center;">From my bed to
                                you in bed somewhere in the karantini. I'm this bored sigh</span>
                            <br> Don't like these emails? <a
                                    style="text-decoration: underline; color: #999999;
                                                                 font-size: 12px; text-align: center;">You are stuck with them </a>.
                        </td>
                    </tr>
                    <tr>
                        <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                            Powered by <a href="http://htmlemail.io" style="color: #999999; font-size: 12px;
                                text-align: center; text-decoration: none;">My ability to adapt code to fit my needs</a>.
                        </td>
                    </tr>
                </table>
            </div>
            <!-- END FOOTER -->
        </td>
    </tr>
</table>
</body>
</html>

"""

part2 = MIMEText(html, "html")



# Add attachment to your message and convert it to string
message.attach(part2)

# We assume that the image file is in the same directory that you run your Python script from
fp = open('screenie.png', 'rb')
image = MIMEImage(fp.read())
fp.close()

image.add_header('Content-ID', '<Mailtrapimage>')
message.attach(image)

text = message.as_string()

# send your email
with smtplib.SMTP("smtp.gmail.com",587) as server:
    print(sender_email)
    server.ehlo()
    server.starttls()
    server.login('', password)
    server.sendmail(
        sender_email, receiver_email, text
    )
    server.quit()

driver.close()
print('Sent') 

